version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - nextjs_node_modules:/app/node_modules
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nextjs_node_modules:
