version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - nextjs_node_modules:/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nextjs_node_modules:
