version: '3.8'

services:
  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn build && yarn start"
    environment:
      - NODE_ENV=production
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "8443:443"
    depends_on:
      - frontend
