/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */
import type { Token } from './token';
import type { AuthDriverDriverVerifyPhonePost200AnyOf } from './authDriverDriverVerifyPhonePost200AnyOf';

export type AuthDriverDriverVerifyPhonePost200 = Token | AuthDriverDriverVerifyPhonePost200AnyOf;
