/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */
import type { Gender } from './gender';
import type { LocationOutput } from './locationOutput';

export interface BasePassenger {
  /** Passenger's balance */
  balance?: number;
  /** Passenger's birth date */
  birthDate: string;
  /** Current object created at time */
  createdAt: string;
  /**
   * Passenger's full name
   * @minLength 3
   */
  fullName: string;
  /** Driver's gender (like Male or Female) */
  gender: Gender;
  /**
   * Current object ID
   */
  id: number;
  /** Passenger's status */
  isActive: boolean;
  /** Passenger's where from location */
  location: LocationOutput;
  /** Passenger's phone number */
  phoneNumber: string;
  /** Current object updated at time */
  updatedAt: string;
}
