/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */
import type { CarPhoto } from './carPhoto';

export interface Car {
  /** Current object created at time */
  createdAt: string;
  /**
   * Current object ID
   */
  id: number;
  /**
   * Car name (like Chevrolet Cobalt)
   * @minLength 2
   */
  name: string;
  /**
   * Number of all seats
   */
  numberOfSeats: number;
  /** Photo of current car (Optional) */
  photo?: CarPhoto;
  /** Current object updated at time */
  updatedAt: string;
}
