/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */

export interface ColorOutput {
  /** Current object created at time */
  createdAt: string;
  /** Color HEX code like #ffffff */
  hex: string;
  /**
   * Current object ID
   */
  id: number;
  /** Color name (like Red or Green) */
  name: string;
  /** Current object updated at time */
  updatedAt: string;
}
