/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */

export interface ColorInput {
  /**
   * Color HEX code like #ffffff
   * @minLength 6
   * @pattern ^#[0-9A-f]{6}[0-9a-f]{0,2}$
   */
  hex: string;
  /** Color name (like Red or Green) */
  name: string;
}
