/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */
import type { Car } from './car';
import type { ColorOutput } from './colorOutput';
import type { Gender } from './gender';
import type { DriverStatus } from './driverStatus';
import type { TripOutput } from './tripOutput';

export interface Driver {
  /** Driver's balance */
  balance: number;
  /** Driver's birth date */
  birthDate: string;
  /** Driver's car */
  car: Car;
  /** Car's number */
  carNumber: string;
  /** Car year (like 2000) */
  carYear: number;
  /** Car color */
  color: ColorOutput;
  /** Current object created at time */
  createdAt: string;
  /** Driver's license number */
  driverLicense: string;
  /** Driver's photo */
  driverPhoto: string;
  /** Driver's full name */
  fullName: string;
  /** Driver's gender (like Male or Female) */
  gender: Gender;
  /**
   * Current object ID
   */
  id: number;
  /** Driver is active */
  isActive: boolean;
  /** Driver's phone number */
  phoneNumber: string;
  /** Driver's rating */
  rating: number;
  /** Driver's status (like Online or Offline) */
  status?: DriverStatus;
  /** Technical passport */
  technicalPassport: string;
  /** All the driver trips */
  trips?: TripOutput[];
  /** Current object updated at time */
  updatedAt: string;
}
