/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */

export type DriverStatus = typeof DriverStatus[keyof typeof DriverStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DriverStatus = {
  online: 'online',
  offline: 'offline',
} as const;
