/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */

export type EditCarCarEditPutParams = {
name: string;
numberOfSeats: number;
carId: number;
};
