/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */

export interface EditCar {
  /**
   * Edit car ID
   */
  carId: number;
  /**
   * Car name (like Chevrolet Cobalt)
   * @minLength 2
   */
  name: string;
  /**
   * Number of all seats
   */
  numberOfSeats: number;
}
