/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */
import type { Gender } from './gender';

export interface EditDriver {
  /**
   * Driver's birth date
   * @pattern ^(0[1-9]|[12][0-9]|3[01])\.(0[1-9]|1[0-2])\.\d{4}$
   */
  birthDate: string;
  /**
   * Car color ID
   */
  carColorId: number;
  /**
   * Driver's car model ID
   */
  carModelId: number;
  /**
   * Car's number
   * @pattern [0-9]{2}[A-Z]{1,2}[0-9]{3}[A-Z]{1,2}
   */
  carNumber: string;
  /**
   * Car year (like 2000)
   */
  carYear: number;
  /**
   * Edit driver ID
   */
  driverId: number;
  /**
   * Driver's license number
   * @pattern [A-Z]{2}[1-9]{7}
   */
  driverLicense: string;
  /** Driver's photo */
  driverPhoto: string;
  /**
   * Driver's full name
   * @minLength 3
   */
  fullName: string;
  /** Driver's gender (like Male or Female) */
  gender: Gender;
  /**
   * Driver's password
   * @minLength 6
   */
  password: string;
  /**
   * Driver's phone number
   * @minLength 13
   * @maxLength 13
   * @pattern ^\+998(90|91|93|94|33)\d{7}$
   */
  phoneNumber: string;
  /**
   * Driver's technical passport
   * @pattern [A-Z]{3}[1-9]{7}
   */
  technicalPassport: string;
}
