/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */
import type { Gender } from './gender';

export interface Passenger {
  /** Passenger's birthday */
  birth_date: string;
  /**
   * Passenger's full name
   * @minLength 3
   */
  fullName: string;
  /** Passenger's gender (like Male or Female) */
  gender: Gender;
  /**
   * Location ID
   */
  locationId: number;
  /**
   * Driver's phone number
   * @minLength 13
   * @maxLength 13
   * @pattern ^\+998(90|91|93|94|33)\d{7}$
   */
  phoneNumber: string;
}
