/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */
import type { PromocodeType } from './promocodeType';

export interface PromocodeOutput {
  /** Current object created at time */
  createdAt: string;
  expiresAt: string;
  /**
   * Current object ID
   */
  id: number;
  promocode: string;
  type: PromocodeType;
  /** Current object updated at time */
  updatedAt: string;
  value: number;
}
