/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */
import type { PromocodeType } from './promocodeType';

export interface PromocodeInput {
  /** Promocode expire date */
  expiresAt: string;
  /** Promocode like TAXOPARK2024 */
  promocode: string;
  /** Promocode type: percentage or amount */
  type: PromocodeType;
  /** Promocode value */
  value: number;
}
