/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */

export interface Session {
  /** Current object created at time */
  createdAt: string;
  /**
   * Current object ID
   */
  id: number;
  ipAddress: string;
  platform: string;
  refreshToken: string;
  /** Current object updated at time */
  updatedAt: string;
}
