/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */

export interface Statistics {
  cars: number;
  drivers: number;
  income: number;
  locations: number;
  passengers: number;
  sms: number;
  trips: number;
}
