/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */
import type { TripInputToDate } from './tripInputToDate';

export interface TripInput {
  /**
   * Trip cost
   */
  cost: number;
  /**
   * Departure location
   */
  departureId: number;
  /**
   * Destination location
   */
  destinationId: number;
  /** Departure date */
  fromDate: string;
  /** Destination date */
  toDate?: TripInputToDate;
}
