/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Taxopark API
 * Taxopark is a company that transports passengers between cities
 * OpenAPI spec version: 1.0.0
 */
import type { Session } from './session';

export interface User {
  /** Current object created at time */
  createdAt: string;
  /** User's email */
  email: string;
  /** User's first Name */
  firstName: string;
  /**
   * Current object ID
   */
  id: number;
  /** User's last Name */
  lastName: string;
  sessions?: Session[];
  /** Current object updated at time */
  updatedAt: string;
}
